apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rawSpansGrouperConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-

    kafka.streams.config = {
      application.id = raw-spans-to-structured-traces-grouping-job
      metrics.recording.level = "{{ .Values.rawSpansGrouperConfig.kafka.streams.config.metricsRecordingLevel }}"
      num.stream.threads = "{{ .Values.rawSpansGrouperConfig.kafka.streams.config.numStreamThreads }}"
      producer.compression.type = gzip
      topology.optimization = all
      bootstrap.servers = "{{ .Values.rawSpansGrouperConfig.kafka.streams.config.bootstrapServers }}"
      auto.offset.reset = "latest"
      auto.commit.interval.ms = 5000
    }

    schema.registry.config {
      schema.registry.url = "{{ .Values.rawSpansGrouperConfig.schema.registry.config.schemaRegistryUrl }}"
      specific.avro.reader = true
    }

    span.groupby.session.window.interval = {{ .Values.rawSpansGrouperConfig.span.groupby.internal }}

    {{- if hasKey .Values.rawSpansGrouperConfig "metrics" }}
    metrics {
      reporter {
        names = {{- toJson .Values.rawSpansGrouperConfig.metrics.reporter.names | trim | nindent 12 }}
      }
    }
    {{- end }}
